# -*- coding: utf-8 -*-
"""load .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wXaBPO8ebpfdFZRetn0Qbh-KAtdV8I6j

#EXTRACCIÓN DE DATOS
"""

def load(predict):
    data.to_csv(predict)